spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/notes_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:notes_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:notes_password}
# spring.mvc.pathmatch.matching-strategy=ant_path_matcher

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true